[tool.ruff]
preview = true
fix = true
unsafe-fixes = false
line-length = 120

[tool.ruff.lint]
select = [
    "F",   # Pyflakes
    "E",   # Pycodestyle Error
    "I",   # isort
    "N",   # pep8-naming (N)
    "W",   # Pycodestyle Warning
    "ANN", # flake8-annotations (ANN)
    "S",   # flake8-bandit
    "PL"   # Pylint
]

ignore = [
    "F401",    # imported but unused
    "F403",   
    "F405", 
    "ANN101",  # Missing type annotation for self in method
    "PLC1901", # compare-to-empty-string
    "PLR0904", # Too many public methods
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments in function definition
    "PLR0914", # Too many local variables
    "PLR0915", # Too many statements
    "PLR0917", # Too many positional arguments
    "PLR2004", # Magic value used in comparison
    "PLW2901"  # Outer variable overwritten by inner target
]

[tool.ruff.lint.pydocstyle]
convention = "google"

